runtime: php55
api_version: 1

handlers:
- url: /
  script: index.html

- url: /index\.html
  script: index.html

- url: /js
  static_dir: js

- url: /js/app\.js
  script: js/app.js

- url: /tpl
  static_dir: tpl

- url: /tpl/item\.html
  script: tpl/item.html

- url: /php/(.+\.php)$
  script: php/\1

env_variables:
  MYSQL_DSN: mysql:unix_socket=/cloudsql/video-search-and-save:us-central1:youtube-video-search-and-save;dbname=video
  MYSQL_USER: root
  MYSQL_PASSWORD: p@ssw0rd